SELECT
	WEEK(CURDATE()),
	SUBDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 1 DAY
	) AS DOMIGO,
	DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY) AS SEGUNDA,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 1 DAY
	) AS TERCA,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 2 DAY
	) AS QUARTA,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 3 DAY
	) AS QUINTA,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 4 DAY
	) AS SEXTA,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 5 DAY
	) AS SABADO,
	ADDDATE(
		DATE_ADD(CURDATE(), INTERVAL - WEEKDAY(CURDATE()) DAY), INTERVAL 6 DAY
	) AS DOMIGO_2,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-', DAY(CURRENT_DATE())
		), INTERVAL 7 DAY
	) AS SEMANA_ANTERIOR,
	CONCAT(
		YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
	) AS MES_ATUAL,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
		), INTERVAL 1 MONTH
	) AS MESES_ANTERIOR,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
		), INTERVAL 3 MONTH
	) AS ULTIMOS_TRES_MESES,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
		), INTERVAL 6 MONTH
	) AS ULTIMOS_SEIS_MESES,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
		), INTERVAL 12 MONTH
	) AS ULTIMO_DOZE_MESES,
	SUBDATE(
		ADDDATE(
		 	CONCAT(
				YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
			), INTERVAL 1 MONTH
		), INTERVAL 1 DAY
	) AS ULTIMO_DIA_MES_ATUAL,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-', MONTH(CURRENT_DATE()), '-01'
		), INTERVAL 1 DAY
	) AS ULTIMO_DIA_MES_ANTERIOR,
	CONCAT(
		YEAR(CURRENT_DATE()), '-01-01'
	) AS ANO_ATUAL,
	SUBDATE(
	 	CONCAT(
			YEAR(CURRENT_DATE()), '-01-01'
		), INTERVAL 1 YEAR
	) AS ANO_ANTERIOR
